dist: trusty
sudo: required
language: node_js
node_js:
- node
- '9'
addons:
  firefox: latest
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable fluxbox
services:
- docker
env:
  global:
  - DOCKER_COMPOSE_VERSION="1.13.0"
  - REGISTRY_USER=scaleitrobot
  - secure: ilGiPlG6eBuOMWDbBUXeQM/Br6EcnA8isgy3GpJWeGayfGHP40NOBv8EBeOfU4DN3e7M30j533NmPPBRTit+4YL4mFGWIEeGHIoR66yPo63ONBB8cRi52KwsbQjCIeiD3tsyYrtecY0g6tXYpygLzEAZrW5nYT+ITEPZi3G24/V8Qkty0+jtHer4s4ktWr93RqLysHBrUbzfRFHJgrM4BnBgu5pkvxOALEL1ISIOT5Wx1Bw3qYWRiTHNtsnqShoYtIY7iYu813cpo3xYzzQ8GmdaP7Kdsk1AGGAp1QeKklQ/OQ4QWlXMuJSyEyDW54wPKM3cMRHCcueNB4NLqvR9f9zbAJ+ZaBHpvJlToqG1pnrsrsi8EzKJY3JO7oHwjOqE43wNKlbPsdMgw/EAKZO8IZv4JL7I7K66pvHo25hWcxczuzdnng11OyzqmS5A3SZdOzVjouQxY26VnQBbhvTMMNkzv6TN8H8fOB2q9rcf/XBQ9+E6SXwLEV0gkCQw1ZML4ht5qabIKrGeipdZuIayF9jxM3JQRBXhlmnPcAtu5pq8TKXzG88Yom9RV54d5/20SM22mEVbGZ3mFBNjqbZx1ayQTa7s9HmWpDI/uN0FmkxkrSra8As1bEi7A1gYFkRwb5NEW3SGL/lUX6VtrsQjJVkhsRq940v/xUEp2ko9Xw0=
before_install:
- sudo apt-get update
install:
- docker-compose --version
- docker --version
- npm install --prefix ./Domain\ Software/workflow/
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 3
- fluxbox >/dev/null 2>&1 &
- docker-compose up --build -d
script:
- docker ps
- npm test --prefix ./Domain\ Software/workflow/
after_script:
- docker-compose down
before_deploy:
- docker login -u "$REGISTRY_USER" -p "$REGISTRY_PASS"
deploy:
  provider: script
  script: docker push scaleit/sapp-workflow-app
  on:
    branch: master
